variable "synapse_rg_name" {}
variable "syapse_rg_location" {}
variable "synapse_sql_server_name" {}
variable "synapse_sa_sql_database_name" {}
variable "permanent_infra_key_vault_name" {}
variable "permanent_infra_rg_name" {}
variable "sql_svradmin_login_name_secret" {}
variable "sql_svradmin_login_password_secret" {}
variable "databricks_resource_group_name" {}
